
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
#from tkinter import Canvas, Entry, Text, Button, PhotoImage
import tkinter as tk
class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.resizable(False, False)
        self.geometry("616x433")
        self.configure(bg = "#E47474")

        self.canvas.place(x = 0, y = 0)
        image_image_1 = tk.PhotoImage(file=self.relative_to_assets("image_1.png"))
        self.canvas.create_image(308.0,126.0,image=image_image_1)

        entry_image_1 = tk.PhotoImage(file=self.relative_to_assets("entry_1.png"))
        self.canvas.create_image(317.0,254.5,image=entry_image_1)
        entry_1 = tk.Entry(bd=0,bg="#F7D7D7",highlightthickness=0)
        entry_1.place(x=178.0,y=236.0,width=278.0,height=35.0)

        entry_image_2 = tk.PhotoImage(file=self.relative_to_assets("entry_2.png"))
        self.canvas.create_image(317.0,315.5,image=entry_image_2)
        entry_2 = tk.Entry(bd=0,bg="#F6D1D1",highlightthickness=0)
        entry_2.place(x=178.0,y=297.0,width=278.0,height=35.0)

        self.canvas.create_text(284.0,246.0,anchor="nw",text="Username",fill="#8D7E7E",
            font=("Inter Regular", 12 * -1)
        )

        self.canvas.create_text(284.0,307.0,anchor="nw",text="Password",fill="#8D7E7E",
            font=("Inter", 12 * -1)
        )

        button_image_1 = tk.PhotoImage(file=self.relative_to_assets("button_1.png"))
        button_1 = tk.Button(image=button_image_1,borderwidth=0,highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
            )
        button_1.place(x=178.0,y=357.0,width=278.0,height=37.0)

        self.canvas.create_text(272.0,401.0,anchor="nw",text="Forgot Password?",
            fill="#FFFFFF",
            font=("Inter", 12 * -1)
        )

    @property
    def canvas(self):
        canvas = tk.Canvas(
            self,
            bg = "#E47474",
            height = 433,
            width = 616,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )
        return canvas
    def relative_to_assets(self,path: str) -> Path:
        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path("./assets")
        return ASSETS_PATH / Path(path)

if __name__ == "__main__":
  app = App()
  app.mainloop()


##################################################################
############ ORIGINAL GENERATED CODE IS BELOW HERE ###############
##################################################################

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


# from pathlib import Path

# # from tkinter import *
# # Explicit imports to satisfy Flake8
# from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


# OUTPUT_PATH = Path(__file__).parent
# ASSETS_PATH = OUTPUT_PATH / Path("./assets")


# def relative_to_assets(path: str) -> Path:
#     return ASSETS_PATH / Path(path)


# window = Tk()

# window.geometry("616x433")
# window.configure(bg = "#E47474")


# canvas = Canvas(
#     window,
#     bg = "#E47474",
#     height = 433,
#     width = 616,
#     bd = 0,
#     highlightthickness = 0,
#     relief = "ridge"
# )

# canvas.place(x = 0, y = 0)
# image_image_1 = PhotoImage(
#     file=relative_to_assets("image_1.png"))
# image_1 = canvas.create_image(
#     308.0,
#     126.0,
#     image=image_image_1
# )

# entry_image_1 = PhotoImage(
#     file=relative_to_assets("entry_1.png"))
# entry_bg_1 = canvas.create_image(
#     317.0,
#     254.5,
#     image=entry_image_1
# )
# entry_1 = Entry(
#     bd=0,
#     bg="#F7D7D7",
#     highlightthickness=0
# )
# entry_1.place(
#     x=178.0,
#     y=236.0,
#     width=278.0,
#     height=35.0
# )

# entry_image_2 = PhotoImage(
#     file=relative_to_assets("entry_2.png"))
# entry_bg_2 = canvas.create_image(
#     317.0,
#     315.5,
#     image=entry_image_2
# )
# entry_2 = Entry(
#     bd=0,
#     bg="#F6D1D1",
#     highlightthickness=0
# )
# entry_2.place(
#     x=178.0,
#     y=297.0,
#     width=278.0,
#     height=35.0
# )

# canvas.create_text(
#     284.0,
#     246.0,
#     anchor="nw",
#     text="Username",
#     fill="#8D7E7E",
#     font=("Inter Regular", 12 * -1)
# )

# canvas.create_text(
#     284.0,
#     307.0,
#     anchor="nw",
#     text="Password",
#     fill="#8D7E7E",
#     font=("Inter", 12 * -1)
# )

# button_image_1 = PhotoImage(
#     file=relative_to_assets("button_1.png"))
# button_1 = Button(
#     image=button_image_1,
#     borderwidth=0,
#     highlightthickness=0,
#     command=lambda: print("button_1 clicked"),
#     relief="flat"
# )
# button_1.place(
#     x=178.0,
#     y=357.0,
#     width=278.0,
#     height=37.0
# )

# canvas.create_text(
#     272.0,
#     401.0,
#     anchor="nw",
#     text="Forgot Password?",
#     fill="#FFFFFF",
#     font=("Inter", 12 * -1)
# )
# window.resizable(False, False)
# window.mainloop()